### ISSUE TITLE
a question about "file access" can do harm

### ISSUE THREAD

**Issue by LucianoBestia** [rust-secure-code/cargo-geiger#106]
I like the idea of cargo-geiger.
The dependency tree can be pretty deep. We cannot/shouldnot check thoroughly every single crate. Just the one that can do harm.
`unsafe code` is the prime suspect.
But also standard "file access" can be damaging. If a mini crate deep down the tree can read or even write arbitrary files to the file system, that is mostly unwanted side effects. And can be misused.
Some mini crates should be marked #![no_file_access] and #![no_unsafe].
And if the compiler can really assure that this is true at compile time, it would make the crates ecosystem much more trustworthy.
In the case the crate needs file access (for logging), the parent crate should give it access. So the parent crate knows what is going on and can limit the folders, filenames, and can watch and react if misused.

**Comment by anderejd** [comment]
Expanding the scope of cargo geiger seem reasonable to me. Feel free to push in this direction, experiment with a draft PR or keep the discussion going here. My time for open source is in short supply at the moment though so my participation will be quite limited.
