### ISSUE TITLE
server to geiger every crate version and publish to cargo-crev 

### ISSUE THREAD

**Issue by LucianoBestia** [rust-secure-code/cargo-geiger#108]
I built a web site to show cargo-crev reviews:
example:
https://web.crev.dev/rust-reviews/crate/num-traits/
My goal is to enable developers to read reviews before they choose to include a crate in their project.
Geiger is a great tool, but it works locally on the base of cargo.toml. So the developer has already choosen the dependency.
My idea is to build a server that downloads new versions from crates.io, geiger them and writes a review with the findings. I think there should be a person to add some more knowledge about the found unsafe code. Then push it to its GitHub repository. Cargo-crev stores reviews publicly in GitHub repositories.
From there the users of cargo-crev can fetch this reviews and read them. Also web.crev.dev fetches this repo and shows it publicly on the web.
Please, take a look on the web-site https://web.crev.dev/rust-reviews/ 
I appreciate you opinion on this.

**Comment by anderejd** [comment]
Love love love the idea of providing crev reviews as a website! Doing some kind of website for cargo geiger results has been something I've been hoping to find the time for myself or even better, someone else doing it instead :) Please report back in this github issue if and when you push ahead with this idea!
