### ISSUE TITLE
cfg-gated unsafe.

### ISSUE THREAD

**Issue by vi** [rust-secure-code/cargo-geiger#13]
Shall it handle `#[cfg(feature=...)]` and other optional unsafe code?

**Comment by anderejd** [comment]
Good question. I think there’s value in gathering unsafe stats without splitting the results per feature, but it could also be interesting to tag each unsafe usage with related cfg attributes. The scanning could always look for cfg attributes and allow optional presentation based on extra command line flags.

**Comment by vi** [comment]
I mean primarily making `cargo geiger --all-features`, `cargo geiger --no-default-features` work.

**Comment by anderejd** [comment]
> I mean primarily making cargo geiger --all-features, cargo geiger --no-default-features work.

Ah, yes. That makes sense.

**Comment by pinkforest** [comment]
tokio/tokio 
cargo geiger --no-default-features
23/136     1245/9291    73/189 1/17    61/286

cargo geiger --all-features
108/136    7453/9291    172/189 17/17   192/286

cargo geiger (it's nothing included by default)
23/136     1245/9291    73/189 1/17    61/286

cargo geiger --features fs
23/136     1251/9291    73/189 1/17    63/286

implementation wise It goes to cargo CompileOptions from_cli currently #226 but we are aiming to decouple

Closing as it's been resolved - re-open if any issues that we can reproduce.

There were some other errors related to another issue I've linked here.
