### ISSUE TITLE
Use cargo_metadata to explore the dependency tree.

### ISSUE THREAD

**Issue by anderejd** [rust-secure-code/cargo-geiger#16]
Switch out the `cargo` API pieces currently used for exploring the dependency graph and use  <https://crates.io/crates/cargo_metadata> instead.

Found here: https://github.com/sfackler/cargo-tree/issues/41

This is a subtask of #69 

Consider using https://crates.io/crates/krates as part of this migration.

**Comment by jmcconnell26** [comment]
Hi, 

I was looking to start working on this issue, and raised this PR 
https://github.com/rust-secure-code/cargo-geiger/pull/110
off the back of this comment
https://github.com/rust-secure-code/cargo-geiger/blob/master/cargo-geiger/src/cli.rs#L138

Would you have any objections to me working on this?

Thanks
Josh

**Comment by tarcieri** [comment]
You might also consider [`cargo-lock`](https://docs.rs/cargo-lock/), which also has an integrated [`petgraph`-based dependency graph](https://docs.rs/cargo-lock/latest/cargo_lock/dependency/tree/struct.Tree.html).

**Comment by anderejd** [comment]
Hello,

Any and all contributions are very much welcome!

In fact, I have been planning to reach out for new contributors for some time, but somehow continously have been finding excuses to do it later. For some background see #87 

The PR looks nice and clean, will merge in a moment.

**Comment by anderejd** [comment]
@tarcieri What's the main differences between cargo-lock and cargo-metadata?

**Comment by jmcconnell26** [comment]
Hey,

That's fantastic, cheers! I'd definitely be keen to start landing a few PR's where there's help needed.

**Comment by anderejd** [comment]
If we can eliminate cargo as a compile time dependency that would be huge. Keep those PRs coming!

**Comment by tarcieri** [comment]
@anderejd `cargo-lock` parses and consumes Cargo.lock directly as a self-contained library. In that regard it should be marginally faster than `cargo_metadata`. If you intend to use any other output from `cargo_metadata` than the crate dependency graph though, it might be better.

**Comment by Shnatsel** [comment]
Sadly `cargo-lock` doesn't cut it in this particular case because it does not allow distinguishing between runtime, build and dev dependencies. And we don't want to search build and development dependencies for unsafe code. Build dependencies have a completely different threat model: unsafe code in build dependencies is not dangerous, but e.g. network access or filesystem operations could be.

Resolving dependency types is surprisingly tricky - `cargo_metadata` shows the raw data from the dependency graph, so that a runtime dependency of a crate that your crate has as a build dependency will still be considered a runtime dependency, while we want to consider it a build dependency for geiger purposes. I have recently implemented splitting crates into build, dev and runtime dependencies _relative to the toplevel crate_ [here](https://github.com/Shnatsel/rust-audit/blob/6e3bf0b2cf95323d0b973d25a89387c298b06499/auditable-serde/src/lib.rs#L127-L163); feel free to steal it.

If you need any more info on this, feel free to ping me [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/146229-wg-secure-code).

**Comment by jmcconnell26** [comment]
I started off with an attempt at refactoring the cli module into its constituent parts, with a view to adding unit tests to ensure that I don't break any functionality. 
https://github.com/rust-secure-code/cargo-geiger/pull/111
I hope this looks OK, please let me know if there are any changes you would like me to make.
Thanks,
Josh

**Comment by jmcconnell26** [comment]
After the refactoring from the previous PR, I've added in a few unit tests here:
https://github.com/rust-secure-code/cargo-geiger/pull/112
I hope you think this looks OK, it's been very useful for me to get to grips with the code base.
If there are any changes you would like me to make, please let me know.
Thanks,
Josh

**Comment by anderejd** [comment]
#112 looks great! Merged.

**Comment by jmcconnell26** [comment]
Once the change from https://github.com/rust-secure-code/cargo-geiger/pull/139 has been made, the majority of the usages of `cargo::core` should be contained to the `utils` module (which I'm not thrilled on the name of, and would like to rename to `mapping` if there are no objections?).
This will leave the following tasks to be completed before the `cargo::core` dependency can be removed:

- Get the `ManifestMetadata` from a `cargo_metadata::Package` or `cargo_metadata::PackageId` [ ] 
- Create a function that returns the same result as `deps_not_replaced` on `PackageSet` without using `cargo::core` [ ]
- Handle extracting the root package from a virtual manifest using `cargo_metadata` [ ]
- Create a function that returns the same result as `replace` on `PackageId` [ ]
- Create a function to construct `cargo_geiger_serde::PackageId ` from `cargo_metadata::PackageId` [ ]

**Comment by anderejd** [comment]
> the `utils` module (which I'm not thrilled on the name of, and would like to rename to `mapping` if there are no objections?)

@jmcconnell26 `mapping` is certainly a better name, let's rename it.

**Comment by jmcconnell26** [comment]
Awesome! Have landed https://github.com/rust-secure-code/cargo-geiger/pull/140 to make the change.

**Comment by anderejd** [comment]
@jmcconnell26 Do you know of anything more that needs to be done before we close this issue?

**Comment by jmcconnell26** [comment]
@anderejd, I think this should be everything on this issue.
I have left some usages of the `cargo::core` packages in the dev dependencies only of the mapping module, to be used to ensure that there is feature parity when unit testing.
I can pull together a list of the remaining `cargo` crate usages for the parent issue if that would be helpful?

**Comment by anderejd** [comment]
> I have left some usages of the cargo::core packages in the dev dependencies only of the mapping module, to be used to ensure that there is feature parity when unit testing.
I can pull together a list of the remaining cargo crate usages for the parent issue if that would be helpful?

@jmcconnell26 A comment informing about the purpose of testing for each such `cargo::core` usage could make it easier to remove it later when implementing #69.
