### ISSUE TITLE
Run `cargo audit` as part of CI builds

### ISSUE THREAD

**Issue by anderejd** [rust-secure-code/cargo-geiger#166]
`cargo audit` exists and we should use it as part of CI builds:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/3704611/102694334-a0420500-4220-11eb-9605-eb5edc9a4c23.png">

**Comment by brightly-salty** [comment]
This can be easily accomplished by using [this GitHub action](https://github.com/marketplace/actions/rust-audit-check).

**Comment by anderejd** [comment]
Excuse my ignorance, I need to study GitHub Actions... the linked GitHub action looks over engineered and seems to depend on nodejs. Why is that better than a single command `cargo audit --check`? Is it how GitHub actions must be implemented?

**Comment by brightly-salty** [comment]
I probably know even less than you. I do know that cargo-audit recommends using that GitHub Action rather than running `cargo audit` directly [here](https://github.com/RustSec/cargo-audit#using-cargo-audit-on-github-action).

**Comment by tarcieri** [comment]
There's some functionality in the action which is nice, like auto-filing issues for security vulnerabilities.

If you don't care about that you can just use a simple action which installs, caches, and runs `cargo-audit`, although that won't change anything about using Node since that's what Actions is using behind the scenes.

**Comment by anderejd** [comment]
> cargo-audit recommends using that GitHub Action rather than running cargo audit directly here

@brightly-salty Thanks for the link and the info, let's go with the official recommendation and use the GitHub action.

> There's some functionality in the action which is nice, like auto-filing issues for security vulnerabilities.
>
> If you don't care about that you can just use a simple action which installs, caches, and runs cargo-audit, although that won't change anything about using Node since that's what Actions is using behind the scenes.

@tarcieri If nodejs is what GitHub Actions require, then I have no problem with it, I just prefer to avoid nodejs when possible. Let's use the mentioned GitHub action.

**Comment by jmcconnell26** [comment]
Raised https://github.com/rust-secure-code/cargo-geiger/pull/184 to run cargo audit against head at midnight

**Comment by anderejd** [comment]
Great work, thanks! Closing.
