### ISSUE TITLE
Can't run tests for the package geiger 

### ISSUE THREAD

**Issue by qrilka** [rust-secure-code/cargo-geiger#172]
I was trying to understand the project test suite and stumbled upon the fact that both `cargo -p geiger test` and `cargo test` in the `geiger` directory fail for me with the following error:

```
kirill@kdesktop:~/ws/rust/cargo-geiger$ cargo test -p geiger 
   Compiling cargo-geiger-serde v0.1.0 (/home/kirill/ws/rust/cargo-geiger/cargo-geiger-serde)
error[E0277]: the trait bound `semver::Version: package_id::_::_serde::Deserialize<'_>` is not satisfied
  --> cargo-geiger-serde/src/package_id.rs:12:5
   |
12 |     /// Package version
   |     ^^^^^^^^^^^^^^^^^^^ the trait `package_id::_::_serde::Deserialize<'_>` is not implemented for `semver::Version`
   |
   = note: required by `package_id::_::_serde::de::SeqAccess::next_element`

error[E0277]: the trait bound `semver::Version: package_id::_::_serde::Deserialize<'_>` is not satisfied
  --> cargo-geiger-serde/src/package_id.rs:12:5
   |
12 |     /// Package version
   |     ^^^^^^^^^^^^^^^^^^^ the trait `package_id::_::_serde::Deserialize<'_>` is not implemented for `semver::Version`
   |
   = note: required by `package_id::_::_serde::de::MapAccess::next_value`

error[E0277]: the trait bound `semver::Version: package_id::_::_serde::Serialize` is not satisfied
  --> cargo-geiger-serde/src/package_id.rs:12:5
   |
12 |     /// Package version
   |     ^^^^^^^^^^^^^^^^^^^ the trait `package_id::_::_serde::Serialize` is not implemented for `semver::Version`
   |
   = note: required by `package_id::_::_serde::ser::SerializeStruct::serialize_field`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `cargo-geiger-serde`.

To learn more, run the command again with --verbose.
```

**Comment by anderejd** [comment]
The tests run in CI seems to pass, did you get the tests to work locally?

**Comment by qrilka** [comment]
CI uses `cargo test` in the root directory of the project - that works fine for me too, the problem is specifically about  the crate `geiger`.

**Comment by anderejd** [comment]
This comment seems to indicate that cargo ignores feature flags of the workspace if using the -p flag:

https://github.com/microsoft/windows-rs/issues/432#issuecomment-765671037

Seems like a bug in cargo to me...?

**Comment by qrilka** [comment]
Sounds like a bug but I don't think if its applicable here - workspace doesn't define features and `cargo-geiger-serde` wasn't setting the required feature. Or maybe I miss something?

**Comment by anderejd** [comment]
I haven't looked close enough at it so I'm just guessing here, that some other crate in the dependency tree of the entire workspace could be settings the related cargo feature flag when building tests for the entire workspace.
