### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value

### ISSUE THREAD

**Issue by surechen** [rust-secure-code/cargo-geiger#205]
Hi, when I use command cargo geiger. I get following error in both stable(1.52.1) and nightly(1.54.0-nightly) rustc:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }, "/usr/local/src/rust/rust_build_demo/C:\\Users\\chenshuo\\.cargo\\registry\\src\\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\\futures-core-0.3.13\\src\\lib.rs")', /root/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/cargo-geiger-0.11.1/src/scan/default.rs:98:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

stack backtrace:
   0: rust_begin_unwind
             at /rustc/f94942d8421dc4b1da86d07069571ddb43127235/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/f94942d8421dc4b1da86d07069571ddb43127235/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/f94942d8421dc4b1da86d07069571ddb43127235/library/core/src/result.rs:1355:5
   3: cargo_geiger::scan::default::scan
   4: cargo_geiger::scan::default::table::scan_to_table
   5: cargo_geiger::scan::default::scan_unsafe
   6: cargo_geiger::scan::scan
   7: cargo_geiger::main

Could you give me some help? Thanks

**Comment by anderejd** [comment]
> /usr/local/src/rust/rust_build_demo/C:\Users\chenshuo\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\futures-core-0.3.13\src\lib.rs

That's an interesting path. Are you building under WSL perhaps or inside git bash on windows?

**Comment by surechen** [comment]
> > /usr/local/src/rust/rust_build_demo/C:\Users\chenshuo.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\futures-core-0.3.13\src\lib.rs
> 
> That's an interesting path. Are you running under WSL perhaps or inside git bash on windows?

Hi, thank you very much for pointing out the problem. I cloned the project using git in Windows and then copied the whole project to Linux. I try to clone the project directly in Linux and did not encounter this problem again.
