### ISSUE TITLE
Locking issue when cargo geiger is stopped in the middle of analysis

### ISSUE THREAD

**Issue by nasifimtiazohi** [rust-secure-code/cargo-geiger#207]
If `cargo geiger` is stopped in the middle of analysis, it presumably fails to free lock on build directory of the package that it was analyzing. The subsequent cargo geiger run then hangs with below message,

`Blocking waiting for file lock on build directory`

I then have to manually run `cargo clean` to get rid of this issue

**Comment by pinkforest** [comment]
@nasifimtiazohi I can't replicate this with current stable rustc / cargo nor nightly on Linux ubuntu LTS

My replication attempt was to Ctrl-C middle of analysis as Ctrl-C is considered stopping it as title suggests and which emits SIGINT / SIGBREAK that is typically caught but not sure whether current cargo actually even relies on it.

Was this more of a crash situation that went SIGTERM ?

Are you running some IDE or some other environment that results into multiple cargo instances at same time?

Note I've bumped cargo dep to latest 0.58.0 but the flock code is still there in Cargo and pretty much same -

Also what OS are you using and what type of filesystem does it implement for the build directory?

If you run this on container what type of filesystem the container runs? If I can have your Dockerfile I could replicate it.

Cargo's flock.rs is relying on fs flock and NFS is known to be problematic on this sense and this has some code in Cargo to bypass NFS broken locking where the detection for that is shown on fn is_on_nfs_mount.

cargo-0.58.0/src/cargo/util/flock.rs - lines 314-
```
   let msg = format!("waiting for file lock on {}", msg);
   config.shell().status_with_color("Blocking", &msg, Cyan)?;

    lock_block().with_context(|| format!("failed to lock file: {}", path.display()))?;
    return Ok(());
```

**Comment by pinkforest** [comment]
This is an underlying cargo feature which we have no control of and is of potentially environment issue with flock.

Re-open if minimum reproducible example provided / environment details we can replicate.
