### ISSUE TITLE
Cargo geiger fails with resource temporarily unavailable 

### ISSUE THREAD

**Issue by nasifimtiazohi** [rust-secure-code/cargo-geiger#209]
While trying to run cargo-geiger on the project [polkadot](https://github.com/paritytech/polkadot), cargo-geiger fails with below error:
`error: `cargo metadata` exited with an error: error: failed to start `cargo metadata`: Resource temporarily unavailable (os error 35)\n\nCaused by:\n  Resource temporarily unavailable (os error 35)\n"`

Note that, `cargo build` works fine on the project and I have tried rebooting my machine to give it a clean state. But seems like every time it fails at some arbitrary crate after some time with resource being unavailable. Another  error message says `warning: clang: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable`.

**Comment by pinkforest** [comment]
@nasifimtiazohi what OS are you running? errno 35 is just POSIX EGAIN hard to know which thing failed.

In OSX could be process limit per user that you can check from sysctl. 

What does ps -aux | wc -l say?

What CLI options are you using to run build / cargo geiger?

Also a log output what happened could be helpful.

**Comment by pinkforest** [comment]
This seems to be an environment issue which I cannot replicate - related to #207 

I suspect it is the same environment flock issue emanating from cargo which could lead up to 

Will re-open if OS and environment information / replication is known and potentially some tracing to get to bottom of this.
