### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by anderejd** [rust-secure-code/cargo-geiger#210]
It's become obvious to me that I don't have time for open source experiments for the foreseeable future. If you or your organization want to maintain Cargo Geiger, reply in this github issue.

**Comment by pinkforest** [comment]
Hi @anderejd I am a big fan and want to see this used way more than now. I am planning to to do auto-repo scanning service using Geiger that feeds from crates.io and analyses rs crate dependencies from all the repos. I could put my hand up for this.

**Comment by tarcieri** [comment]
The Secure Code WG (speaking at least for myself) would be happy to have it continue to live here and maintain it. If there's someone else outside of the WG who's particularly interested we could also grant them permission to this repo (and hopefully also join the WG).

**Comment by pinkforest** [comment]
@tarcieri sounds like the ideal arrangement. do you have a discord hangout? i have stuff to contribute.

**Comment by tarcieri** [comment]
I'm in the `#crypto-and-security` channel of https://discord.gg/rust-lang-community

**Comment by 8573** [comment]
(For reference, maintainership was previously discussed in #87.)

**Comment by pinkforest** [comment]
> (For reference, maintainership was previously discussed in #87.)

README.md is referring to this issue - README that was updated couple of months back.

The repo has been largely sitting idle since August otherwise looking at issues / deps?

**Comment by anderejd** [comment]
This is a reply to an email from @pinkforest from yesterday.

I would be delighted to see anyone take over active maintenance and maybe even pushing the project forward with new features etc. It will not be possible for me to find the time to contribute to this project going forward.

@tarcieri If you would like to keep this project as part of rust-secure-code then please invite @pinkforest to replace me as maintainer of this project.

Thoughts? Questions?

**Comment by tarcieri** [comment]
@anderejd done!
