### ISSUE TITLE
Multithreading in scanning phase

### ISSUE THREAD

**Issue by ilyatrefilov** [rust-secure-code/cargo-geiger#269]
This issue is created to discuss/propose changes to current scanning phase in cargo-geiger.
Initially i made an implementation with rayon lib in this PR #268

**Comment by pinkforest** [comment]
#268 on tokio-rs/tokio shaved ~6 seconds and I don't see the scanning progress popping up that I have to wait

Good stuff @ilyatrefilov :rocket:

**Comment by pinkforest** [comment]
I don't think there is anything else to do for now so closing. Re-open if issue / feature identified.
