### ISSUE TITLE
panics if target directory is read only

### ISSUE THREAD

**Issue by Person-93** [rust-secure-code/cargo-geiger#280]
I noticed this when working on the docker image.

Things like `cargo clean` and `cargo build` need to write to the target directory and the result of resolving files is unwrapped [here](https://github.com/rust-secure-code/cargo-geiger/blob/master/cargo-geiger/src/scan/default.rs#L105-L106).

Perhaps instead of calling clean and build it should just build but explicitly set the output directory to be a temporary directory.

**Comment by pinkforest** [comment]
This is re-done in 0.12 that will not have this problem.

For a bug fix on 0.11 instead of panic we can just clean up the unwrap with proper error message - feel free to send a PR
