### ISSUE TITLE
Add optional json output format

### ISSUE THREAD

**Issue by anderejd** [rust-secure-code/cargo-geiger#35]
`--json` or something similar.

**Comment by icefoxen** [comment]
Related: #10 

This would be nice for my side-project too; aim me at the right data structures and if/when I need this I'll implement it.  Do we want this to be a feature flag so we don't *always* need to build serde, or is that fine?

**Comment by anderejd** [comment]
> aim me at the right data structures and if/when I need this I'll implement it.

All the functions related to printing the tree needs to be separated from the source code scanning, in particular this function needs some refocusing:
https://github.com/anderejd/cargo-geiger/blob/master/src/lib.rs#L829

When that separation is done the json feature should only require a bit of serde attribute sprinkling on top.

> Do we want this to be a feature flag so we don't always need to build serde, or is that fine?

I think it's good to have it on by default, cargo-geiger already depends on serde and serde-json... and most of the remaining crates.io.

**Comment by stephaneyfx** [comment]
Should this be closed given that #115 was merged?

**Comment by anderejd** [comment]
Yes! :)
