### ISSUE TITLE
git tag for 0.11.4 missing

### ISSUE THREAD

**Issue by jcgruenhage** [rust-secure-code/cargo-geiger#364]
https://crates.io/crates/cargo-geiger has version 0.11.4 already, but it has no git tag.

cc @pinkforest, because she's uploaded the release to crates.io

**Comment by pinkforest** [comment]
@jcgruenhage  

Oops sorry about that - should be there now - need to move to my monorepo friendly GitHub release action to streamline this

Cheers

**Comment by pinkforest** [comment]
Closing as resolved - re-open if any issues pls :)

**Comment by jcgruenhage** [comment]
Thanks for fixing this so quickly! Streamlining this with a CI job sounds good, but until then I'll mention it if I notice it :)
