### ISSUE TITLE
Panic while source tree is watched by RLS

### ISSUE THREAD

**Issue by parasyte** [rust-secure-code/cargo-geiger#78]
Running `cargo geiger` while [Rust Language Server](https://github.com/rust-lang/rls) is watching my source tree in Atom results in the following panic (inconsistently... It is easiest to trigger the panic by stopping the cargo geiger build - Ctrl+C - then start `cargo geiger` while RLS is also rebuilding).

<details><summary>Backtrace</summary>

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Cargo("could not remove build directory")', src/libcore/result.rs:1189:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:82
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1189
  15: core::result::Result<T,E>::unwrap
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libcore/result.rs:957
  16: cargo_geiger::cli::run_scan_mode_default
             at cargo-geiger/src/cli.rs:272
  17: cargo_geiger::real_main
             at cargo-geiger/src/main.rs:314
  18: cargo_geiger::main
             at cargo-geiger/src/main.rs:336
  19: std::rt::lang_start::{{closure}}
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libstd/rt.rs:61
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:81
  23: std::panicking::try
             at src/libstd/panicking.rs:265
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:395
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  26: std::rt::lang_start
             at /rustc/412f43ac5b4ae8c3599e71c6972112e9be4758fa/src/libstd/rt.rs:61
  27: <cargo_geiger::FormatError as core::fmt::Debug>::fmt
```
</details>

https://github.com/anderejd/cargo-geiger/blob/69c6f0e38fc75de614eee29472b722d8b2ee487b/cargo-geiger/src/cli.rs#L272

You can probably reproduce this with RLS in VSCode as well.

The `unwrap` on the `Result` type is definitely not great error handling, but I'm wondering if there is a better way to handle cleaning in general? Specifying the package name will at least fix the problem with RLS, since `cargo clean -p <package-name>` does not remove the `./target/rls` subdirectory, but should still be suitable for geiger's cleaning needs.

**Comment by anderejd** [comment]
Hi! Thanks for the excellent bug report!

> The unwrap on the Result type is definitely not great error handling, but I'm wondering if there is a better way to handle cleaning in general? Specifying the package name will at least fix the problem with RLS, since cargo clean -p <package-name> does not remove the ./target/rls subdirectory, but should still be suitable for geiger's cleaning needs.

I agree, the unwrap should be fixed. In my opinion every Rust program that aren't a simple script-like program, all unwraps should be replaced by proper error handling. The suggestion to look into `cargo clean -p ...` to actually avoid causing the error seems like a good idea to me.

December will be a crazy busy month for me, so any and all help would be much appreciated.
