### ISSUE TITLE
Maintenance and organization

### ISSUE THREAD

**Issue by anderejd** [rust-secure-code/cargo-geiger#87]
Hey everyone!

This project needs at least another active maintainer to keep the issues from building up and to provide users with timely and well written replies to new issues.

I've posted a related question here: https://github.com/rust-secure-code/wg/issues/36

Would it make more sense to create a github organization for the tool or to move it into an existing one, like the organization liked to above?

I would like to see some discussion on the topic before making a decision.

**Comment by tarcieri** [comment]
I think `cargo-geiger` is very much in the sprit of the Secure Code WG and we'd be happy to provide a home for it

**Comment by Shnatsel** [comment]
I'd solicit maintainers on Rust forums or Reddit. I already have more projects to take care of than I have the time for, as does @tarcieri, so it would be hard for any of us to commit to maintenance.

**Comment by tarcieri** [comment]
I can provide some basic PR review and if you'd like, manage releases, but I don't have time to do any active development work on it.

**Comment by anderejd** [comment]
> I can provide some basic PR review and if you'd like, manage releases, but I don't have time to do any active development work on it.

That sounds like a 100% improvement if I do the same and keep looking in every now and then. I'm not planning on disappearing from github, just looking to involve a few more individuals.

I could simply invite more users to this repository, but I personally get a more welcoming impression when projects have a github organization owning the central upsteam repository rather than an individual developer, like myself in this case.

Do you think moving to rust-secure-wg would be a good first step before reaching out to people on reddit and the official forum? Or should we do it the other way around and start inviting people first?

**Comment by tarcieri** [comment]
> Do you think moving to rust-secure-wg would be a good first step before reaching out to people on reddit and the official forum? Or should we do it the other way around and start inviting people first?

I think it'd be better to move it first, then make an announcement about the new location and that you're looking for additional volunteers to maintain it.

**Comment by anderejd** [comment]
Transfer request has been sent to @tarcieri, it seems like you will need to transfer it to rust-secure-code since I cannot create repositories there.

**Comment by tarcieri** [comment]
@anderejd thanks! I was able to move it over here:

https://github.com/rust-secure-code/cargo-geiger

I also created a team for `cargo-geiger` admins and sent you an invite:

https://github.com/orgs/rust-secure-code/teams/cargo-geiger-admins

Let me know if there's anyone else I should add.

**Comment by anderejd** [comment]
Nice 👍 

> Let me know if there's anyone else I should add.

If @icefoxen is interested to join that would be cool since he started the whole thing with https://github.com/icefoxen/cargo-osha
