### ISSUE TITLE
Reconfigure CI

### ISSUE THREAD

**Issue by anderejd** [rust-secure-code/cargo-geiger#88]
We need to setup a new Azure pipeline with access to this repository. Would you @tarcieri like me to send an access request from the old Azure pipelines organization (https://dev.azure.com/cargo-geiger/cargo-geiger) or would you prefer to create a new one?

**Comment by tarcieri** [comment]
I've never used Azure Pipelines before. If it's simple enough to keep the existing organization I think that's fine.

**Comment by anderejd** [comment]
There we go, the CI is now up and running again. Updated the status badge URL in: https://github.com/rust-secure-code/cargo-geiger/commit/97de8c02eace31c116dc6af6ff83aeacbc7a2172
