### ISSUE TITLE
Should the README's position statement on unsafe code be adjusted for the new ownership?

### ISSUE THREAD

**Issue by 8573** [rust-secure-code/cargo-geiger#90]
The README says the following:

> It is however the opinion of the author of this project that libraries choosing to abstain from unsafe Rust usage when possible should be promoted.

Now that the crate is owned by the Secure Code Working Group, I suggest either identifying "the author" or changing the sentence to state the opinion of the Working Group, whichever you consider appropriate.

**Comment by anderejd** [comment]
This sound like a good idea to me. @tarcieri & @Shnatsel do you have a suggestion on the rephrasing?

**Comment by tarcieri** [comment]
There's a bit of a similar statement on the Safety Dance repo:

https://github.com/rust-secure-code/safety-dance

> This is a place for people to communicate about auditing unsafe code in core Rust crates and replacing it with safe code where feasible.

It might be good to discuss, as a group, a common statement we can use across projects like this. I think this statement is fairly close to what I believe, but maybe slightly lacking in nuance.

**Comment by anderejd** [comment]
I'm fine with anything the rust-secure-code group decides. Regarding the original wording "abstain", that was intended to hint at the allure of exploring low level and often accidentally unsound optimizations.

**Comment by pinkforest** [comment]
@8573 - wanna send a PR to fix that? :purple_heart:

**Comment by pinkforest** [comment]
Okay how does this look:
https://github.com/rust-secure-code/cargo-geiger/pull/304
