### ISSUE TITLE
Cargo.toml vs. Cargo.lock

### ISSUE THREAD

**Issue by anderejd** [rust-secure-code/cargo-geiger#91]
https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

There are reports of Cargo.toml and Cargo.lock not working as intended. We need a minimal reproducible example as the next step.

**Comment by pinkforest** [comment]
Can't see the issue and no reproduction as of now - closing this, re-opening if seen anywhere.

**Comment by pinkforest** [comment]
@anderejd I did some investigation work .. or went down the deep rabbithole .. and found the real issue - 

It's a long story - enjoy
https://github.com/rust-secure-code/cargo-geiger/issues/83#issuecomment-1006431479
